name = "htcomp"
author = "Oscar Mojica"
copyright  = "Copyright (c) 2023, Oscar Mojica"
license = "BSD-3"
description = "Modern Fortran Edition of the Anderson scheme to evaluate Hankel Transform integrals"
homepage = "https://github.com/ofmla/digital_filtering_HT_integrals"
keywords = ["digital filtering", "Hankel Transform", "Anderson scheme", "283 points"]

[build]
auto-executables = false
auto-examples = false
auto-tests = true

[library]
source-dir = "src"

[install]
library = true
